// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	runner "megacron/system/runner"

	mock "github.com/stretchr/testify/mock"
)

// RunnerInterface is an autogenerated mock type for the RunnerInterface type
type RunnerInterface struct {
	mock.Mock
}

// Run provides a mock function with given fields: commandWithArgs, feedBackChannel
func (_m *RunnerInterface) Run(commandWithArgs string, feedBackChannel chan<- runner.RunResult) {
	_m.Called(commandWithArgs, feedBackChannel)
}

type mockConstructorTestingTNewRunnerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewRunnerInterface creates a new instance of RunnerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRunnerInterface(t mockConstructorTestingTNewRunnerInterface) *RunnerInterface {
	mock := &RunnerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
